spring.application.name=campus-connect
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/campus_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true