spring.application.name=campus-vortex
server.port=${PORT:8080}

# Cloud MySQL Database Configuration (Aiven Live Instance)
spring.datasource.url=jdbc:mysql://mysql-18620fab-promitkumar786-501f.g.aivencloud.com:23305/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_2aJQ9irXpyBIhumKXm7

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true